version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.0"

    steps:
      - checkout

      - run:
          name: Before Install
          command: |
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8
      
      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: pod install

      # Build the app and run tests
     - run:
         name: Build and run tests
         command: fastlane circleci
