# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Venues.xcworkspace", scheme: "Venues")
  end
  lane :beta do
  build_app(scheme: "Venues")
  sync_code_signing(type: "appstore")    # see code signing guide for more information
  build_app(scheme: "Venues")
  upload_to_testflight
  slack(message: "Successfully distributed a new beta build")
  end

end
