 update_fastlane(nightly: true)

 default_platform(:ios)

 platform :ios do
  
 desc "Certs"
  lane :certificates do
    #match(type: "appstore")
    match(type: "development")
  end

  desc "CI build"
  lane :ci_build do
    certificates

  # Test
    # scan(
  #    workspace: "Venues.xcworkspace",
  #    devices: ["iPhone X"],
  #    scheme: "Venues",
  #    clean: true
  #   )
  end

  desc "Circle CI lane"
  lane :circleci do
    setup_circle_ci
    ci_build
  end
  
#desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Venues.xcworkspace", scheme: "VenuesUITests")
  end
  
# lane :beta do
#   build_app(scheme: "Venues")
#   sync_code_signing(type: "development")    # see code signing guide for more information
#   build_app(scheme: "Venues")
#   upload_to_testflight
#   slack(message: "Successfully distributed a new beta build")
#   end

end
